# Generated by Django 5.1.1 on 2025-03-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momentum', '0006_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_login_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
