# Generated by Django 5.1.1 on 2025-03-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momentum', '0008_mindfulnesslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlog',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='workout_type',
            field=models.CharField(choices=[('strength', 'Strength'), ('cardio', 'Cardio')], default='strength', max_length=20),
        ),
    ]
